all_strategies_all_datasets_single_random_seed:
    { EXP_GRID_DATASET: [1-39], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                #OPTIMAL_GREEDY_10,
                #OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0], EXP_GRID_NUM_QUERIES: [5], EXP_GRID_BATCH_SIZE: [5], EXP_GRID_LEARNER_MODEL: [RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0], METRICS: [Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics] }
only_random: {
        EXP_GRID_DATASET: [1-39],
        EXP_GRID_STRATEGY:
            [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                OPTIMAL_GREEDY_10,
            ],
        #OPTIMAL_GREEDY_20,
        #OPTIMAL_BSO,
        #OPTIMAL_TRUE,
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
        EXP_GRID_START_POINT: [1-5],
        METRICS:
            [
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

local_SynDs: {
        EXP_GRID_DATASET: [Chess10, Chess100, Chess250],
        EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                #OPTIMAL_GREEDY_10,
                #OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_START_POINT: [1-5],
        EXP_GRID_NUM_QUERIES: [20],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1],
        METRICS:
            [
                Pickled_Learner_Model,
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

full_exp: { EXP_GRID_DATASET: [1-39], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                OPTIMAL_GREEDY_10,
                OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ], METRICS: [Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0-19], EXP_GRID_NUM_QUERIES: [20], EXP_GRID_BATCH_SIZE: [1, 5, 10], EXP_GRID_LEARNER_MODEL: [MLP, RBF_SVM, RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0-4] } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

local_SynDs2: { EXP_GRID_DATASET: [BigChess60, BigChess10], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                #OPTIMAL_GREEDY_10,
                #OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [1-5], EXP_GRID_NUM_QUERIES: [20], EXP_GRID_BATCH_SIZE: [1, 5], EXP_GRID_LEARNER_MODEL: [RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1], METRICS: [Pickled_Learner_Model, Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics] } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

local_SynDs_Spiral: { EXP_GRID_DATASET: [Spiral], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                #OPTIMAL_GREEDY_10,
                #OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [1-5], EXP_GRID_NUM_QUERIES: [20], EXP_GRID_BATCH_SIZE: [1, 5], EXP_GRID_LEARNER_MODEL: [RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1], METRICS: [Pickled_Learner_Model, Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics] } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

test_exp: {
        EXP_GRID_DATASET: [Iris, Chess10],
        EXP_GRID_STRATEGY:
            [
                ALIPY_RANDOM,
                PLAYGROUND_MIXTURE,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_START_POINT: [1-5],
        EXP_GRID_NUM_QUERIES: [5],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF, MLP],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1],
        METRICS:
            [
                Pickled_Learner_Model,
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],
