all_strategies_all_datasets_single_random_seed: {
        EXP_GRID_DATASET: [1-34],
        EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                ALIPY_QUIRE,
                OPTIMAL_BSO,
                OPTIMAL_TRUE,
                OPTIMAL_GREEDY,
                LIBACT_UNCERTAINTY,
                LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                LIBACT_ALBL,
                LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                #ALIPY_BMDR,
                #ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_START_POINT: [1-5],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RBF_SVM],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
    } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],
only_random:
    {
        EXP_GRID_DATASET: [1-39],
        EXP_GRID_STRATEGY:
            [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF], #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
        EXP_GRID_START_POINT: [1-5],
    }

local_SynDs: {
        EXP_GRID_DATASET: [Chess10, Chess100, Chess1000],
        EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                #ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                #ALIPY_CORESET_GREEDY,
                ALIPY_QUIRE,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                #OPTIMAL_GREEDY,
                LIBACT_UNCERTAINTY,
                LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_VR,
                LIBACT_HINTSVM,
                LIBACT_EER,
                LIBACT_ALBL,
                LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_START_POINT: [1-5],
        EXP_GRID_NUM_QUERIES: [20],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1],
    } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

optimal_alipy_random: { EXP_GRID_DATASET: [1-39], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                ALIPY_QUIRE,
                OPTIMAL_BSO,
                OPTIMAL_TRUE,
                OPTIMAL_GREEDY,
                #LIBACT_UNCERTAINTY,
                #LIBACT_QBC,
                #LIBACT_DWUS,
                #LIBACT_QUIRE,
                #LIBACT_VR,
                #LIBACT_HINTSVM,
                #LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                #PLAYGROUND_GRAPH_DENSITY,
                #PLAYGROUND_HIERARCHICAL_CLUSTER,
                #PLAYGROUND_INFORMATIVE_DIVERSE,
                #PLAYGROUND_KCENTER_GREEDY,
                #PLAYGROUND_MARGIN,
                #PLAYGROUND_MIXTURE,
                #PLAYGROUND_MCM,
                #PLAYGROUND_UNIFORM,
                #PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
            ], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0-99], EXP_GRID_NUM_QUERIES: [20], EXP_GRID_BATCH_SIZE: [1, 5, 10], EXP_GRID_LEARNER_MODEL: [RBF_SVM, MLP, RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0-4] } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

refactoring_test:
    {
        EXP_GRID_DATASET: [1],
        EXP_GRID_STRATEGY: [ALIPY_RANDOM, ALIPY_UNCERTAINTY_LC],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [5],
        EXP_GRID_LEARNER_MODEL: [RF], #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
        EXP_GRID_START_POINT: [1],
    }

refactoring_test_new:
    {
        EXP_GRID_DATASET: [1],
        EXP_GRID_STRATEGY: [ALIPY_RANDOM, ALIPY_UNCERTAINTY_LC],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [5],
        EXP_GRID_LEARNER_MODEL: [RF], #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
        EXP_GRID_START_POINT: [1],
    }
