all_strategies_all_datasets_single_random_seed:
    { EXP_GRID_DATASET: [1-39], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                OPTIMAL_GREEDY_10,
                OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
                SMALLTEXT_LEASTCONFIDENCE,
                SMALLTEXT_PREDICTIONENTROPY,
                SMALLTEXT_BREAKINGTIES,
                #SMALLTEXT_BALD,
                SMALLTEXT_EMBEDDINGKMEANS,
                SMALLTEXT_GREEDYCORESET,
                SMALLTEXT_LIGHTWEIGHTCORESET,
                SMALLTEXT_CONTRASTIVEAL,
                SMALLTEXT_DISCRIMINATIVEAL,
                #SMALLTEXT_CVIAR,
                # SMALLTEXT_SEALS,
                SMALLTEXT_RANDOM,
                # SKACTIVEML_EXPECTED_MODEL_OUTPUT_CHANGE,
                #SKACTIVEML_EXPECTED_MODEL_VARIANCE_REDUCTION,
                #SKACTIVEML_KL_DIVERGENCE_MAXIMIZATION,
                SKACTIVEML_MC_EER_LOG_LOSS,
                SKACTIVEML_MC_EER_MISCLASS_LOSS,
                SKACTIVEML_VOI_UNLABELED,
                SKACTIVEML_VOI_LABELED,
                SKACTIVEML_VOI,
                #SKACTIVEML_EXPECTED_MODEL_CHANGE,
                SKACTIVEML_QBC,
                #SKACTIVEML_EPISTEMIC_US,
                #SKACTIVEML_DDDD,
                SKACTIVEML_US_MARGIN,
                SKACTIVEML_US_LC,
                SKACTIVEML_US_ENTROPY,
                SKACTIVEML_EXPECTED_AVERAGE_PRECISION,
                SKACTIVEML_DWUS,
                #SKACTIVEML_DUAL_STRAT,
                SKACTIVEML_COST_EMBEDDING,
                SKACTIVEML_DAL,
                #SKACTIVEML_GREEDY_TARGET_SPACE,
                #SKACTIVEML_GREEDY_IMPROVED,
                #SKACTIVEML_GREEDY_FEATURE_SPACE,
                SKACTIVEML_MCPAL,
                SKACTIVEML_QBC_VOTE_ENTROPY,
                SKACTIVEML_QUIRE,
            ], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0], EXP_GRID_NUM_QUERIES: [5], EXP_GRID_BATCH_SIZE: [5], EXP_GRID_LEARNER_MODEL: [MLP, RF, RBF_SVM], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0], METRICS: [Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics] }

test:
    {
        EXP_GRID_DATASET: [Iris, wine_origin],
        EXP_GRID_STRATEGY:
            [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
        EXP_GRID_START_POINT: [1-5],
        METRICS:
            [
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    }

test2:
    {
        EXP_GRID_DATASET: [Iris, wine_origin],
        EXP_GRID_STRATEGY:
            [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                OPTIMAL_GREEDY_10,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [20],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF, DT],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1],
        EXP_GRID_START_POINT: [1-5],
        METRICS:
            [
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    }
only_random: {
        EXP_GRID_DATASET: [1-104],
        EXP_GRID_STRATEGY:
            [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                OPTIMAL_GREEDY_10,
            ],
        #OPTIMAL_GREEDY_20,
        #OPTIMAL_BSO,
        #OPTIMAL_TRUE,
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [3],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0],
        EXP_GRID_START_POINT: [1-5],
        METRICS:
            [
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    } #, DT, MNB, GNB, RBF_SVM, LINEAR_SVM, POLY_SVM, MLP, LBFGS_MLP, LR],

full_exp: { EXP_GRID_DATASET: [1-39], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                OPTIMAL_GREEDY_10,
                OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
                SMALLTEXT_LEASTCONFIDENCE,
                SMALLTEXT_PREDICTIONENTROPY,
                SMALLTEXT_BREAKINGTIES,
                #SMALLTEXT_BALD,
                SMALLTEXT_EMBEDDINGKMEANS,
                SMALLTEXT_GREEDYCORESET,
                SMALLTEXT_LIGHTWEIGHTCORESET,
                SMALLTEXT_CONTRASTIVEAL,
                SMALLTEXT_DISCRIMINATIVEAL,
                #SMALLTEXT_CVIAR,
                # SMALLTEXT_SEALS,
                SMALLTEXT_RANDOM,
                # SKACTIVEML_EXPECTED_MODEL_OUTPUT_CHANGE,
                #SKACTIVEML_EXPECTED_MODEL_VARIANCE_REDUCTION,
                #SKACTIVEML_KL_DIVERGENCE_MAXIMIZATION,
                SKACTIVEML_MC_EER_LOG_LOSS,
                SKACTIVEML_MC_EER_MISCLASS_LOSS,
                SKACTIVEML_VOI_UNLABELED,
                SKACTIVEML_VOI_LABELED,
                SKACTIVEML_VOI,
                #SKACTIVEML_EXPECTED_MODEL_CHANGE,
                SKACTIVEML_QBC,
                #SKACTIVEML_EPISTEMIC_US,
                #SKACTIVEML_DDDD,
                SKACTIVEML_US_MARGIN,
                SKACTIVEML_US_LC,
                SKACTIVEML_US_ENTROPY,
                SKACTIVEML_EXPECTED_AVERAGE_PRECISION,
                SKACTIVEML_DWUS,
                #SKACTIVEML_DUAL_STRAT,
                SKACTIVEML_COST_EMBEDDING,
                SKACTIVEML_DAL,
                #SKACTIVEML_GREEDY_TARGET_SPACE,
                #SKACTIVEML_GREEDY_IMPROVED,
                #SKACTIVEML_GREEDY_FEATURE_SPACE,
                SKACTIVEML_MCPAL,
                SKACTIVEML_QBC_VOTE_ENTROPY,
                SKACTIVEML_QUIRE,
            ], METRICS: [Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0-19], EXP_GRID_NUM_QUERIES: [20], EXP_GRID_BATCH_SIZE: [1, 5, 10], EXP_GRID_LEARNER_MODEL: [MLP, RBF_SVM, RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0-4] }

full_exp_alipy_random:
    {
        EXP_GRID_DATASET: [1-104],
        EXP_GRID_STRATEGY: [ALIPY_RANDOM],
        METRICS:
            [
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_START_POINT: [0-19],
        EXP_GRID_NUM_QUERIES: [100],
        EXP_GRID_BATCH_SIZE: [1, 5, 10],
        EXP_GRID_LEARNER_MODEL: [MLP, RBF_SVM, RF],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0-4],
    }

full_exp_v2: { EXP_GRID_DATASET: [1-104], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                OPTIMAL_GREEDY_10,
                OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
                SMALLTEXT_LEASTCONFIDENCE,
                SMALLTEXT_PREDICTIONENTROPY,
                SMALLTEXT_BREAKINGTIES,
                #SMALLTEXT_BALD,
                SMALLTEXT_EMBEDDINGKMEANS,
                SMALLTEXT_GREEDYCORESET,
                SMALLTEXT_LIGHTWEIGHTCORESET,
                SMALLTEXT_CONTRASTIVEAL,
                SMALLTEXT_DISCRIMINATIVEAL,
                #SMALLTEXT_CVIAR,
                # SMALLTEXT_SEALS,
                SMALLTEXT_RANDOM,
                # SKACTIVEML_EXPECTED_MODEL_OUTPUT_CHANGE,
                #SKACTIVEML_EXPECTED_MODEL_VARIANCE_REDUCTION,
                #SKACTIVEML_KL_DIVERGENCE_MAXIMIZATION,
                SKACTIVEML_MC_EER_LOG_LOSS,
                SKACTIVEML_MC_EER_MISCLASS_LOSS,
                SKACTIVEML_VOI_UNLABELED,
                SKACTIVEML_VOI_LABELED,
                SKACTIVEML_VOI,
                #SKACTIVEML_EXPECTED_MODEL_CHANGE,
                SKACTIVEML_QBC,
                #SKACTIVEML_EPISTEMIC_US,
                #SKACTIVEML_DDDD,
                SKACTIVEML_US_MARGIN,
                SKACTIVEML_US_LC,
                SKACTIVEML_US_ENTROPY,
                SKACTIVEML_EXPECTED_AVERAGE_PRECISION,
                SKACTIVEML_DWUS,
                #SKACTIVEML_DUAL_STRAT,
                SKACTIVEML_COST_EMBEDDING,
                SKACTIVEML_DAL,
                #SKACTIVEML_GREEDY_TARGET_SPACE,
                #SKACTIVEML_GREEDY_IMPROVED,
                #SKACTIVEML_GREEDY_FEATURE_SPACE,
                SKACTIVEML_MCPAL,
                SKACTIVEML_QBC_VOTE_ENTROPY,
                SKACTIVEML_QUIRE,
            ], METRICS: [Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0-19], EXP_GRID_NUM_QUERIES: [100], EXP_GRID_BATCH_SIZE: [1, 5, 10], EXP_GRID_LEARNER_MODEL: [MLP, RBF_SVM, RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0-4] }

full_exp_jan: { EXP_GRID_DATASET: [1-104], EXP_GRID_STRATEGY: [
                ALIPY_RANDOM,
                ALIPY_UNCERTAINTY_LC,
                ALIPY_UNCERTAINTY_MM,
                ALIPY_UNCERTAINTY_ENTROPY,
                ALIPY_UNCERTAINTY_DTB,
                ALIPY_GRAPH_DENSITY,
                ALIPY_CORESET_GREEDY,
                #OPTIMAL_BSO,
                #OPTIMAL_TRUE,
                OPTIMAL_GREEDY_10,
                OPTIMAL_GREEDY_20,
                LIBACT_UNCERTAINTY_LC,
                LIBACT_UNCERTAINTY_SM,
                LIBACT_UNCERTAINTY_ENT,
                #LIBACT_QBC,
                LIBACT_DWUS,
                LIBACT_QUIRE,
                LIBACT_EER,
                #LIBACT_ALBL,
                #LIBACT_HIERARCHICAL_SAMPLING,
                PLAYGROUND_GRAPH_DENSITY,
                PLAYGROUND_HIERARCHICAL_CLUSTER,
                PLAYGROUND_INFORMATIVE_DIVERSE,
                PLAYGROUND_KCENTER_GREEDY,
                PLAYGROUND_MARGIN,
                PLAYGROUND_MIXTURE,
                PLAYGROUND_MCM,
                PLAYGROUND_UNIFORM,
                PLAYGROUND_BANDIT,
                ALIPY_QBC,
                ALIPY_EXPECTED_ERROR_REDUCTION,
                ALIPY_BMDR,
                ALIPY_SPAL,
                ALIPY_LAL,
                ALIPY_DENSITY_WEIGHTED,
                SMALLTEXT_LEASTCONFIDENCE,
                SMALLTEXT_PREDICTIONENTROPY,
                SMALLTEXT_BREAKINGTIES,
                #SMALLTEXT_BALD,
                SMALLTEXT_EMBEDDINGKMEANS,
                SMALLTEXT_GREEDYCORESET,
                SMALLTEXT_LIGHTWEIGHTCORESET,
                SMALLTEXT_CONTRASTIVEAL,
                SMALLTEXT_DISCRIMINATIVEAL,
                #SMALLTEXT_CVIAR,
                # SMALLTEXT_SEALS,
                SMALLTEXT_RANDOM,
                # SKACTIVEML_EXPECTED_MODEL_OUTPUT_CHANGE,
                #SKACTIVEML_EXPECTED_MODEL_VARIANCE_REDUCTION,
                #SKACTIVEML_KL_DIVERGENCE_MAXIMIZATION,
                SKACTIVEML_MC_EER_LOG_LOSS,
                SKACTIVEML_MC_EER_MISCLASS_LOSS,
                SKACTIVEML_VOI_UNLABELED,
                SKACTIVEML_VOI_LABELED,
                SKACTIVEML_VOI,
                #SKACTIVEML_EXPECTED_MODEL_CHANGE,
                SKACTIVEML_QBC,
                #SKACTIVEML_EPISTEMIC_US,
                #SKACTIVEML_DDDD,
                SKACTIVEML_US_MARGIN,
                SKACTIVEML_US_LC,
                SKACTIVEML_US_ENTROPY,
                SKACTIVEML_EXPECTED_AVERAGE_PRECISION,
                SKACTIVEML_DWUS,
                #SKACTIVEML_DUAL_STRAT,
                SKACTIVEML_COST_EMBEDDING,
                SKACTIVEML_DAL,
                #SKACTIVEML_GREEDY_TARGET_SPACE,
                #SKACTIVEML_GREEDY_IMPROVED,
                #SKACTIVEML_GREEDY_FEATURE_SPACE,
                SKACTIVEML_MCPAL,
                SKACTIVEML_QBC_VOTE_ENTROPY,
                SKACTIVEML_QUIRE,
            ], METRICS: [Predicted_Samples, Selected_Indices, Standard_ML_Metrics, Timing_Metrics], EXP_GRID_RANDOM_SEED: [0], EXP_GRID_START_POINT: [0-19], EXP_GRID_NUM_QUERIES: [100], EXP_GRID_BATCH_SIZE: [1, 5, 10], EXP_GRID_LEARNER_MODEL: [MLP, RBF_SVM, RF], EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0-4] }

arr_bug:
    {
        EXP_GRID_DATASET: [arrythmia],
        EXP_GRID_STRATEGY: [ALIPY_RANDOM],
        EXP_GRID_RANDOM_SEED: [0],
        EXP_GRID_NUM_QUERIES: [20],
        EXP_GRID_BATCH_SIZE: [1, 5],
        EXP_GRID_LEARNER_MODEL: [RF, DT],
        EXP_GRID_TRAIN_TEST_BUCKET_SIZE: [0, 1],
        EXP_GRID_START_POINT: [1-5],
        METRICS:
            [
                Predicted_Samples,
                Selected_Indices,
                Standard_ML_Metrics,
                Timing_Metrics,
            ],
    }
